title: Guan Ming's Homepage
page-top-title: Guan Ming
top-section-bg-text: Experimental Physics
home-subtitle: Guan Ming&ensp;|&ensp;管 明
copyright-text: '&copy; Guan Ming 2023-2024. All Rights Reserved.'
